name: Connect to Local Database

on: [push]

jobs:
  connect-to-db:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull SQL Server Docker Image
      run: docker pull mcr.microsoft.com/mssql/server:2022-latest

    - name: Set up MS SQL Server
      run: |
        # Start MS SQL Server (replace with your actual start command)
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=MyP@ssw0rd2022@BEEBOI@PASSWORDY' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
    - name: Wait for MS SQL Server to start
      run: sleep 15  # Adjust as needed to wait for the server to initialize

    - name: Connect to Database
      run: |
        # Example connection string
        CONNECTION_STRING="Server=localhost,1433;Database=EmployeeHub;User Id=sa;Password=MyP@ssw0rd2022@BEEBOI@PASSWORDY;"
        # Run a simple query using sqlcmd
        echo "SELECT 'Connection established' AS Result" | sqlcmd -S localhost,1433 -U sa -P MyP@ssw0rd2022@BEEBOI@PASSWORDY -d EmployeeHub
        # Output a marker
        echo "::set-output name=connection_status::connected"
        # Use the connection status in subsequent steps or for debugging
        echo "Connection Status: ${{ steps.connect_to_db.outputs.connection_status }}"
