name: Connect to Local Database

on: [push]

jobs:
  connect-to-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up MS SQL Server
      run: |
        # Start MS SQL Server (replace with your actual start command)
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=MyP@ssw0rd2022@BEEBOI@PASSWORDY' -p 1433:1433 -d mcr.microsoft.com/mssql/server

    - name: Wait for MS SQL Server to start
      run: sleep 15  # Adjust as needed to wait for the server to initialize

    - name: Connect to Database
      run: |
        # Example connection string
        CONNECTION_STRING="Server=localhost,1433;Database=EmployeeHub;User Id=sa;Password=MyP@ssw0rd2022@BEEBOI@PASSWORDY;"

        # Use the connection string in your scripts or commands
        echo "Connection String: $CONNECTION_STRING"

        # Run your database-related commands or tests here
        # For example: dotnet ef database update
